### ISSUE TITLE
Current version?

### ISSUE THREAD

**Issue by Ashton-W** [buildtools-version-taps/homebrew-swiftformat-versions-tap#1]
Is it the purpose of this tap to also include the current version?

I'm wanting to do `brew install swiftformat@0.29.5` and it works, instead of needing to know that `brew install swiftformat` will install 0.29.5 right now, but not in the future.

#2 PR adding `swiftformat@0.29.5`. Thanks for maintaining this - desperately needed to use brew with sanity.

**Comment by Lutzifer** [comment]
oh, somehow I didn't get noticed about the issue

**Comment by Lutzifer** [comment]
was autoupdated and the sha fixed. thx for the PR though :-)
